import React from 'react';
import { Page, Text, View } from '@react-pdf/renderer';
import { pdfStyles } from '@/lib/pdf/styles';

export function PageWrapper({
  title,
  pageNumber,
  generatedAt,
  children,
}: {
  title: string;
  pageNumber: number;
  generatedAt: string;
  children: React.ReactNode;
}) {
  return (
    <Page size="A4" style={pdfStyles.page}>
      <View style={pdfStyles.pageHeader}>
        <Text style={pdfStyles.pageHeaderTitle}>{title}</Text>
        <Text style={pdfStyles.pageHeaderLogo}>FinWise</Text>
      </View>

      {children}

      <View style={pdfStyles.pageFooter}>
        <Text style={pdfStyles.footerText}>Generated by FinWise</Text>
        <Text style={pdfStyles.footerText}>{generatedAt}</Text>
        <Text style={pdfStyles.footerText}>{`Page ${pageNumber}`}</Text>
      </View>
    </Page>
  );
}

