import XLSX from 'xlsx-js-style';
import { XLS } from './styles';

type CellStyle = Record<string, unknown>;

export function cell(v: unknown, s: CellStyle, z?: string): XLSX.CellObject {
  let t: XLSX.CellObject['t'] = 's';
  if (typeof v === 'number') t = 'n';
  else if (v instanceof Date) t = 'd';
  const c: XLSX.CellObject = { v: v as XLSX.CellObject['v'], s, t };
  if (z) c.z = z;
  return c;
}

export function labelCell(text: string, extraStyle?: CellStyle) {
  return cell(text, { ...XLS.label, ...extraStyle });
}

export function inputCell(v: number, fmt: string = XLS.fmt.currency) {
  return cell(v, XLS.input, fmt);
}

export function formulaCell(v: number, fmt: string = XLS.fmt.currency, alt = false) {
  return cell(v, alt ? XLS.altRow : XLS.formula, fmt);
}

export function titleCell(text: string) {
  return cell(text, XLS.title);
}

export function subtitleCell(text: string) {
  return cell(text, XLS.subtitle);
}

export function sectionHeaderCell(text: string) {
  return cell(text, XLS.sectionHeader);
}

export function columnHeaderCell(text: string) {
  return cell(text, XLS.columnHeader);
}

export function subtotalCell(v: number, fmt: string = XLS.fmt.currency) {
  return cell(v, XLS.subtotal, fmt);
}

export function totalLabelCell(text: string) {
  return cell(text, XLS.totalLabel);
}

export function totalCell(v: number, fmt: string = XLS.fmt.currency) {
  return cell(v, XLS.total, fmt);
}

export function footerCell(text: string) {
  return cell(text, XLS.footer);
}

export function blankCell() {
  return cell('', XLS.formula);
}

// Build a sheet from a 2D array of XLSX.CellObject
export function aoa2sheet(data: XLSX.CellObject[][]): XLSX.WorkSheet {
  const ws: XLSX.WorkSheet = {};
  for (let r = 0; r < data.length; r++) {
    for (let c = 0; c < data[r].length; c++) {
      if (data[r][c] !== undefined && data[r][c] !== null) {
        const ref = XLSX.utils.encode_cell({ r, c });
        ws[ref] = data[r][c];
      }
    }
  }
  const maxCols = Math.max(...data.map(row => row.length), 1);
  const range = { s: { r: 0, c: 0 }, e: { r: data.length - 1, c: maxCols - 1 } };
  ws['!ref'] = XLSX.utils.encode_range(range);
  return ws;
}

// Merge cells helper: adds to ws['!merges']
export function addMerge(ws: XLSX.WorkSheet, r1: number, c1: number, r2: number, c2: number) {
  if (!ws['!merges']) ws['!merges'] = [];
  ws['!merges'].push({ s: { r: r1, c: c1 }, e: { r: r2, c: c2 } });
}

// Standard workbook header (rows 0-3): title, subtitle, confidential, blank
export function workbookHeader(toolName: string): XLSX.CellObject[][] {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return [
    [titleCell('FinWise Financial Plan')],
    [subtitleCell(`${toolName} — ${date}`)],
    [cell('CONFIDENTIAL — FOR PERSONAL USE ONLY', { font: { sz: 9, italic: true, color: { rgb: '6b7280' } }, alignment: { horizontal: 'center' } })],
    [blankCell()],
  ];
}

// Standard footer row
export function workbookFooter(): XLSX.CellObject[] {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return [footerCell(`Generated by FinWise | finwise-ochre.vercel.app | ${date}`)];
}

// Download helper
export function downloadWorkbook(wb: XLSX.WorkBook, filename: string) {
  XLSX.writeFile(wb, `${filename}.xlsx`);
}
